### ISSUE TITLE
Could not load file or assembly 'Digipost.Signature.Api.Client.Resources, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Systemet finner ikke angitt fil.

### ISSUE THREAD

**Issue by andreasle** [digipost/signature-api-specification#160]
Hei,
Jeg får en FileNotFoundException: 

`"Could not load file or assembly 'Digipost.Signature.Api.Client.Resources, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Systemet finner ikke angitt fil."`

ved kall til:

`await directClient.Create(job);`

Stacktrace:

```
System.AggregateException
  HResult=0x80131500
  Message=Det oppsto én eller flere feil.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at eDocument.DifiSignering.SignClient.CreateSignatureJob(String docTitle, String docMessage, String docPath, String completionUrl, String rejectionUrl, String errorUrl, List`1 signers) in C:\Bitbucket\edocument\eDocument.DifiSignering\SignClient.cs:line 59
   at eDocument.Api.Controllers.InstancesBaseController.SubmitHelper(JObject json, String customerId, Boolean logIn, String viewerUrl, String paymentId) in C:\Bitbucket\edocument\eDocument.Api\Controllers\InstancesBaseController.cs:line 1036
   at eDocument.Api.Controllers.InstancesController.Submit(JObject json, String customerId, String viewerUrl, Boolean logIn, String paymentId) in C:\Bitbucket\edocument\eDocument.Api\Controllers\InstancesController.cs:line 943
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Digipost.Signature.Api.Client.Resources, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Systemet finner ikke angitt fil.
```
Følgende versjon er installert:

```
<package id="Digipost.Signature.Api.Client.Archive" version="7.0.1" targetFramework="net461" />
<package id="Digipost.Signature.Api.Client.Core" version="7.0.1" targetFramework="net461" />
<package id="Digipost.Signature.Api.Client.Direct" version="7.0.1" targetFramework="net461" />
<package id="Digipost.Signature.Api.Client.Resources" version="7.0.1" targetFramework="net461" />
<package id="Digipost.Signature.Api.Client.Scripts" version="7.0.1" targetFramework="net461" />
```

**Comment by simenstoa** [comment]
Hei, beklager at vi ikke har svart på denne tidligere. Lukker denne nå, men hvis det fortsatt er et problem kan du gjerne opprette et nytt issue i https://github.com/digipost/signature-api-client-dotnet.
